# Generated by Django 5.2.15 on 2026-07-17 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='reels/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('caption', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Na fila'), ('processing', 'Publicando...'), ('published', 'Publicado ✅'), ('failed', 'Falhou ❌')], default='queued', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ig_media_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramaccount')),
                ('caption_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.captionset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for', 'created_at'],
            },
        ),
    ]
