# Generated by Django 5.2.15 on 2026-07-20 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_proxy'),
        ('publisher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='post_type',
            field=models.CharField(choices=[('REELS', 'Reels'), ('FEED', 'Feed'), ('STORY', 'Story')], default='REELS', max_length=10),
        ),
        migrations.CreateModel(
            name='PostLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('REELS', 'Reels'), ('FEED', 'Feed'), ('STORY', 'Story')], default='REELS', max_length=10)),
                ('video_file', models.FileField(upload_to='loops/')),
                ('caption', models.TextField(blank=True)),
                ('interval_days', models.IntegerField(default=7)),
                ('last_posted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
