# Generated by Django 5.2.15 on 2026-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_scheduledpost_post_type_postloop'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='share_to_feed',
            field=models.BooleanField(default=True),
        ),
    ]
