# Generated by Django 5.2.15 on 2026-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_scheduledpost_share_to_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='story_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
