# Generated by Django 5.2.15 on 2026-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_scheduledpost_story_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postloop',
            name='video_file',
            field=models.FileField(max_length=500, upload_to='loops/'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='video_file',
            field=models.FileField(max_length=500, upload_to='reels/'),
        ),
    ]
