# Generated by Django 5.2.15 on 2026-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_alter_postloop_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='clean_mode',
            field=models.CharField(choices=[('none', 'Sem limpeza'), ('light', 'Limpeza leve'), ('ultra', 'Ultra clean')], default='light', max_length=10),
        ),
    ]
