# Generated by Django 5.2.15 on 2026-07-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_audio_file_alter_mediaasset_file'),
        ('publisher', '0006_scheduledpost_clean_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postloop',
            name='interval_days',
        ),
        migrations.AddField(
            model_name='postloop',
            name='clean_mode',
            field=models.CharField(choices=[('none', 'Sem limpeza'), ('light', 'Limpeza leve'), ('ultra', 'Ultra clean')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='postloop',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loops', to='library.mediafolder'),
        ),
        migrations.AddField(
            model_name='postloop',
            name='interval_minutes',
            field=models.IntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='postloop',
            name='last_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postloop',
            name='share_to_feed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postloop',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, upload_to='loops/'),
        ),
    ]
