# Generated by Django 5.2.15 on 2026-07-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_audio_file_alter_mediaasset_file'),
        ('publisher', '0007_remove_postloop_interval_days_postloop_clean_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postloop',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loops', to='library.audio'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='library.audio'),
        ),
    ]
