# Generated by Django 5.2.16 on 2026-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_postqueue_scheduledpost_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='na_grade',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
