# Generated by Django 5.2.16 on 2026-07-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_scheduledpost_na_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='processing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
