# Generated by Django 5.2.15 on 2026-07-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0012_story_editor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='story_link_label',
            field=models.CharField(blank=True, default='CLIQUE AQUI', max_length=40),
        ),
    ]
