# Generated by Django 5.2.15 on 2026-07-31 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_instagramaccount_totp_seed_enc'),
        ('publisher', '0013_scheduledpost_story_link_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('weekdays', models.CharField(default='', max_length=20)),
                ('hora', models.TimeField()),
                ('post_type', models.CharField(choices=[('REELS', 'Reels'), ('FEED', 'Feed'), ('STORY', 'Story')], default='STORY', max_length=10)),
                ('video_file', models.FileField(max_length=500, upload_to='agenda/')),
                ('thumbnail', models.FileField(blank=True, max_length=500, null=True, upload_to='agenda/')),
                ('caption', models.TextField(blank=True)),
                ('share_to_feed', models.BooleanField(default=True)),
                ('clean_mode', models.CharField(choices=[('none', 'Sem limpeza'), ('light', 'Limpeza leve'), ('ultra', 'Ultra clean')], default='light', max_length=10)),
                ('story_link', models.URLField(blank=True, max_length=500)),
                ('story_link_label', models.CharField(blank=True, default='CLIQUE AQUI', max_length=40)),
                ('espacamento_min', models.IntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ManyToManyField(related_name='agendas', to='instagram.instagramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hora', 'id'],
            },
        ),
    ]
