# Generated by Django 5.2.15 on 2026-08-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0014_agendasemanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='interval_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
