# Generated by Django 5.2.15 on 2026-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0015_scheduledpost_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='variar_auto',
            field=models.BooleanField(default=True),
        ),
    ]
