# Generated by Django 5.2.15 on 2026-08-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0016_scheduledpost_variar_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendasemanal',
            name='clean_mode',
            field=models.CharField(choices=[('none', 'Sem limpeza'), ('ultra', 'Ultra clean')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='postloop',
            name='clean_mode',
            field=models.CharField(choices=[('none', 'Sem limpeza'), ('ultra', 'Ultra clean')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='clean_mode',
            field=models.CharField(choices=[('none', 'Sem limpeza'), ('ultra', 'Ultra clean')], default='none', max_length=10),
        ),
    ]
