# Generated by Django 5.2.15 on 2026-07-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_meta_app_id_user_meta_app_secret_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_app_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_app_secret_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_login_config_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
