# Generated by Django 5.2.15 on 2026-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_instagram_app_id_user_instagram_app_secret_enc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
