# Generated by Django 5.2.15 on 2026-07-21 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('meta_app_id', models.CharField(blank=True, max_length=64)),
                ('meta_app_secret_enc', models.TextField(blank=True)),
                ('meta_login_config_id', models.CharField(blank=True, max_length=64)),
                ('instagram_app_id', models.CharField(blank=True, max_length=64)),
                ('instagram_app_secret_enc', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
