# Generated by Django 5.2.15 on 2026-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_migrar_credenciais_para_metaapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bound_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='publishing_paused',
            field=models.BooleanField(default=False),
        ),
    ]
