# Generated by Django 5.2.15 on 2026-08-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_bound_ip_user_ip_locked_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_meta_apps',
            field=models.IntegerField(default=0, help_text='0 = ilimitado.', verbose_name='Limite de apps Meta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_ig_accounts',
            field=models.IntegerField(default=0, help_text='0 = ilimitado.', verbose_name='Limite de contas do Instagram'),
        ),
    ]
