# Generated by Django 5.2.15 on 2026-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_limites_ilimitados_para_quem_ja_existia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abas_ocultas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
