# Generated by Django 5.2.15 on 2026-07-17 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_username', models.CharField(max_length=150)),
                ('ig_password', models.TextField()),
                ('proxy_url', models.CharField(blank=True, help_text='Ex: http://user:pass@ip:port', max_length=255)),
                ('ig_user_id', models.BigIntegerField(blank=True, null=True)),
                ('profile_pic_url', models.URLField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('connecting', 'Conectando...'), ('active', 'Ativa ✅'), ('challenge_required', 'Código necessário 🔑'), ('2fa_required', '2FA necessário 🔐'), ('session_expired', 'Sessão expirada 🕒'), ('error', 'Erro ❌')], default='connecting', max_length=30)),
                ('session_blob', models.JSONField(blank=True, null=True)),
                ('device_settings', models.JSONField(blank=True, null=True)),
                ('challenge_type', models.CharField(blank=True, max_length=50)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'ig_username')},
            },
        ),
    ]
