# Generated by Django 5.0.6

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='meta_access_token',
            field=models.TextField(blank=True, help_text='Token da API Oficial (Meta Graph)'),
        ),
    ]
