# Generated by Django 5.2.15 on 2026-07-20 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('intensity', models.CharField(choices=[('low', 'Leve'), ('medium', 'Moderado'), ('high', 'Agressivo')], default='low', max_length=10)),
                ('target_hashtag', models.CharField(default='reels', max_length=100)),
                ('counter_date', models.DateField(blank=True, null=True)),
                ('likes_today', models.IntegerField(default=0)),
                ('follows_today', models.IntegerField(default=0)),
                ('views_today', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warmup', to='instagram.instagramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
