# Generated by Django 5.2.15 on 2026-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_warmupconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
