# Generated by Django 5.2.15 on 2026-07-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_migrar_credenciais_para_metaapp'),
        ('instagram', '0005_alter_instagramaccount_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='meta_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.metaapp'),
        ),
    ]
