# Generated by Django 5.2.15 on 2026-07-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_instagramaccount_meta_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='status',
            field=models.CharField(choices=[('connecting', 'Conectando...'), ('active', 'Ativa ✅'), ('challenge_required', 'Código necessário 🔑'), ('2fa_required', '2FA necessário 🔐'), ('session_expired', 'Sessão expirada 🕒'), ('banned', 'Banida/indisponível 🚫'), ('error', 'Erro ❌')], default='connecting', max_length=30),
        ),
    ]
