# Generated by Django 5.2.15 on 2026-07-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_instagramaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='daily_post_limit',
            field=models.IntegerField(default=20),
        ),
    ]
