# Generated by Django 5.2.15 on 2026-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_instagramaccount_daily_post_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='rate_limited_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
