# Generated by Django 5.2.15 on 2026-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_instagramaccount_rate_limited_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='quota_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='quota_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='quota_usage',
            field=models.IntegerField(default=0),
        ),
    ]
