# Generated by Django 5.2.16 on 2026-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_instagramaccount_quota_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='views_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='views_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='views_total',
            field=models.IntegerField(default=0),
        ),
    ]
