# Generated by Django 5.2.16 on 2026-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_instagramaccount_views_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='banned_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='banned_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
