# Generated by Django 5.2.16 on 2026-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_instagramaccount_banned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='ignorar_limites',
            field=models.BooleanField(default=False),
        ),
    ]
