# Generated by Django 5.2.16 on 2026-07-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_instagramaccount_ignorar_limites'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='pausada',
            field=models.BooleanField(default=False),
        ),
    ]
