# Generated by Django 5.2.16 on 2026-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_instagramaccount_pausada'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='modelo',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
