# Generated by Django 5.2.15 on 2026-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_pasta_instagramaccount_pasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='totp_seed_enc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
