# Generated by Django 5.2.15 on 2026-08-01 00:23

from django.db import migrations, models


def subir_limite_padrao(apps, schema_editor):
    """Contas que estavam no default antigo (20) sobem para o novo default (100).
    Quem escolheu outro valor fica como está."""
    InstagramAccount = apps.get_model('instagram', 'InstagramAccount')
    InstagramAccount.objects.filter(daily_post_limit=20).update(daily_post_limit=100)


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_instagramaccount_totp_seed_enc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='daily_post_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.RunPython(subir_limite_padrao, migrations.RunPython.noop),
    ]
