# Generated by Django 5.2.15 on 2026-08-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_warmup_rampup_pacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='health_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='meta_limit_count',
            field=models.IntegerField(default=0),
        ),
    ]
