# Generated by Django 5.2.15 on 2026-08-04 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0022_instagramaccount_health_checked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('ig_username', models.CharField(blank=True, max_length=150)),
                ('senha_enc', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, choices=[('rodando', 'Rodando'), ('pausada', 'Pausada'), ('contingencia', 'Contingência'), ('caiu', 'Caiu'), ('restricao', 'Com restrição'), ('', '—')], default='', max_length=20)),
                ('conectada', models.BooleanField(default=False)),
                ('caiu', models.BooleanField(default=False)),
                ('restricao', models.BooleanField(default=False)),
                ('contingencia', models.BooleanField(default=False)),
                ('tem_2fa', models.BooleanField(default=False)),
                ('codigo_2fa_enc', models.TextField(blank=True)),
                ('codigo_token_enc', models.TextField(blank=True)),
                ('ultimo_login', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='instagram.instagramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['owner', 'ordem'], name='instagram_f_owner_i_f306a6_idx')],
            },
        ),
    ]
