# Generated by Django 5.2.15 on 2026-08-07 01:53

from django.db import migrations, models


def backfill_publicados(apps, schema_editor):
    """Inicia o contador com o total ATUAL de publicados de cada conta, para o
    dashboard não zerar/mudar de repente. Daqui pra frente só incrementa."""
    ScheduledPost = apps.get_model('publisher', 'ScheduledPost')
    InstagramAccount = apps.get_model('instagram', 'InstagramAccount')
    from django.db.models import Count
    por_conta = (ScheduledPost.objects.filter(status='published')
                 .values('account_id').annotate(n=Count('id')))
    for row in por_conta:
        (InstagramAccount.objects.filter(id=row['account_id'])
         .update(publicados_total=row['n']))


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0023_ficha_conta'),
        ('publisher', '0017_remover_clean_mode_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='publicados_total',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_publicados, migrations.RunPython.noop),
    ]
