# Generated by Django 5.2.15 on 2026-08-04 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Só para você achar depois. Não aparece na página.', max_length=120)),
                ('titulo_pagina', models.CharField(default='Conteudo Privado', help_text='Aparece na aba do navegador.', max_length=120)),
                ('imagem_fundo', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('desfoque_fundo', models.IntegerField(default=12, help_text='Desfoque do fundo, em pixels (0 = nítido).')),
                ('brilho_fundo', models.FloatField(default=0.45, help_text='0.1 = bem escuro · 1.0 = imagem original.')),
                ('foto_perfil', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('mostrar_online', models.BooleanField(default=True)),
                ('texto_online', models.CharField(default='Estou online agora', max_length=60)),
                ('nome_exibicao', models.CharField(default='Seu nome', max_length=80)),
                ('descricao', models.CharField(default='Hoje eu resolvi liberar meu **canal privado** por algumas horas...', help_text='Use **texto** para destacar em rosa.', max_length=300)),
                ('btn1_ativo', models.BooleanField(default=True)),
                ('btn1_titulo', models.CharField(default='MEU TELEGRAM', max_length=80)),
                ('btn1_subtitulo', models.CharField(default='CLIQUE AQUI E ACESSE MEU VIP NO TELEGRAM', max_length=120)),
                ('btn1_link', models.URLField(blank=True, max_length=500)),
                ('btn1_icone', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('btn1_cor_a', models.CharField(default='#0088cc', max_length=9)),
                ('btn1_cor_b', models.CharField(default='#00aaff', max_length=9)),
                ('btn2_ativo', models.BooleanField(default=True)),
                ('btn2_titulo', models.CharField(default='Privacy 50% Desconto 🔥', max_length=80)),
                ('btn2_subtitulo', models.CharField(default='CLIQUE AQUI E VEJA NOSSO PRIVACY', max_length=120)),
                ('btn2_link', models.URLField(blank=True, max_length=500)),
                ('btn2_icone', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('btn2_cor_a', models.CharField(default='#ff6b35', max_length=9)),
                ('btn2_cor_b', models.CharField(default='#ff8c42', max_length=9)),
                ('titulo_cards', models.CharField(default='Conteúdos privados', max_length=80)),
                ('desfoque_cards', models.IntegerField(default=6, help_text='Desfoque das miniaturas, em pixels.')),
                ('desfoque_cards_hover', models.IntegerField(default=3, help_text='Desfoque ao passar o mouse (efeito de "espiar").')),
                ('card1_imagem', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('card1_texto', models.CharField(blank=True, default='Vídeos privados de hoje 🔒', max_length=80)),
                ('card2_imagem', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('card2_texto', models.CharField(blank=True, default='Fotos exclusivas 🔒', max_length=80)),
                ('card3_imagem', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('card3_texto', models.CharField(blank=True, default='', max_length=80)),
                ('card4_imagem', models.ImageField(blank=True, max_length=500, null=True, upload_to='pressel/')),
                ('card4_texto', models.CharField(blank=True, default='', max_length=80)),
                ('rodape', models.CharField(blank=True, default='Conteúdo exclusivo para maiores de 18 anos.', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
