# Generated by Django 5.2.15 on 2026-07-17 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('posts', models.IntegerField()),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramaccount')),
            ],
            options={
                'unique_together': {('account', 'date')},
            },
        ),
    ]
