# Generated by Django 5.2.16 on 2026-07-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_caiu', models.BooleanField(default=True)),
                ('falha_publicacao', models.BooleanField(default=True)),
                ('limite_atingido', models.BooleanField(default=True)),
                ('meta_views', models.BooleanField(default=True)),
                ('meta_views_alvo', models.IntegerField(default=10000)),
                ('resumo_diario', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_token_enc', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
