# Generated by Django 5.2.16 on 2026-07-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpreference',
            name='app_lotado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='app_lotado_limite',
            field=models.IntegerField(default=15),
        ),
    ]
