# Generated by Django 5.2.16 on 2026-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alertpreference_app_lotado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpreference',
            name='story_publicado',
            field=models.BooleanField(default=False),
        ),
    ]
